package com.maan.common.exception;

public class ExceptionConstants {

	public static final String DATABASE_ERROR = "THE PROGRAM HAS ENCOUNTERED A DATABASE ERROR";

	public static final String CLASS_NOT_FOUND = "THE PROGRAM HAS ENCOUNTERED A CLASS NOT FOUND ERROR";

	public static final String INSTANTIATION = "THE PROGRAM HAS ENCOUNTERED A INSTANTIATION ERROR";

	public static final String ILLEGAL_ACCESS = "THE PROGRAM HAS ENCOUNTERED A ILLEGAL ACCESS ERROR";

	public static final String NAMING_ERROR = "THE PROGRAM HAS ENCOUNTERED A NAMING ERROR";

	public static final String CONN_CLOSE = "THE PROGRAM HAS ENCOUNTERED AN ERROR WHILE CLOSING CONNECTION";

	public static final String CONN_OPEN = "THE PROGRAM HAS ENCOUNTERED AN ERROR WHILE OPENING CONNECTION";

	public static final String CONN_ROLLBACK = "THE PROGRAM HAS ENCOUNTERED AN ERROR WHILE ROLLBACK";

	public static final String CONN_COMMIT = "THE PROGRAM HAS ENCOUNTERED AN ERROR WHILE COMMIT";

	public static final String AUTHENTICATION = "THE PROGRAM HAS ENCOUNTERED AN ERROR WHILE AUTHENTICATING";

	public static final String OTHER_ERROR = "THE PROGRAM HAS ENCOUNTERED AN ERROR";
}
